apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: {{ .Values.pgadminValues.replicaCount }}
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: {{ .Values.pgadminValues.image.repository }}:{{ .Values.pgadminValues.image.tag }}
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgadminValues.pgadminSecret.name }}
                  key: {{ .Values.pgadminValues.pgadminSecret.emailKey }}
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgadminValues.pgadminSecret.name }}
                  key: {{ .Values.pgadminValues.pgadminSecret.passwordKey }}
          ports:
            - containerPort: {{ .Values.pgadminValues.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
