apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcValues.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvcValues.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvcValues.resources.requests.storage }}